;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;;                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.

(ns euler.euler002)

(defn- gen-fibbo-seq
  "Helper function for second Euler problem:
   Generate lazy Fibonacci sequence"
  []
  ((fn fib [a b]
     (cons a (lazy-seq (fib b (+ a b)))))
   0 1))

(defn solution
  "Solution of second Euler problem.
  Computes the summatory of even Fibonacci numbers below n."
  [n]
  (reduce + (filter even? (take-while #(<= % n) (gen-fibbo-seq)))))
